export const genreOptions = [
  { value: "Electronic", label: "Electronic" },
  { value: "Funk / Soul", label: "Funk / Soul" },
  { value: "Folk, World, & Country", label: "Folk, World, & Country" },
  { value: "Jazz", label: "Jazz" },
  { value: "Latin", label: "Latin" },
  { value: "Hip Hop", label: "Hip Hop" },
  { value: "Stage & Screen", label: "Stage & Screen" },
  { value: "Blues", label: "Blues" },
  { value: "Reggae", label: "Reggae" },
  { value: "Non-Music", label: "Non-Music" },
  { value: "Classical", label: "Classical" },
  { value: "Children's", label: "Children's" },
  { value: "Brass & Military", label: "Brass & Military" },
];
export const countryOptions = [
  { value: "US", label: "US" },
  { value: "UK", label: "UK" },
  { value: "Germany", label: "Germany" },
  { value: "France", label: "France" },
  { value: "Japan", label: "Japan" },
  { value: "Italy", label: "Italy" },
  { value: "Europe", label: "Europe" },
  { value: "Canada", label: "Canada" },
  { value: "Unknown", label: "Unknown" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "Spain", label: "Spain" },
  { value: "Australia", label: "Australia" },
  { value: "Russia", label: "Russia" },
  { value: "Brazil", label: "Brazil" },
  { value: "Sweden", label: "Sweden" },
  { value: "Belgium", label: "Belgium" },
  { value: "Greece", label: "Greece" },
  { value: "Poland", label: "Poland" },
  { value: "Mexico", label: "Mexico" },
  { value: "Finland", label: "Finland" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "Worldwide", label: "Worldwide" },
  { value: "USSR", label: "USSR" },
  { value: "Argentina", label: "Argentina" },
  { value: "Denmark", label: "Denmark" },
  { value: "Portugal", label: "Portugal" },
  { value: "Norway", label: "Norway" },
  { value: "Austria", label: "Austria" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "UK & Europe", label: "UK & Europe" },
  { value: "South Africa", label: "South Africa" },
  { value: "Colombia", label: "Colombia" },
  { value: "Yugoslavia", label: "Yugoslavia" },
  { value: "Hungary", label: "Hungary" },
  { value: "USA & Canada", label: "USA & Canada" },
  { value: "India", label: "India" },
  { value: "Ukraine", label: "Ukraine" },
  { value: "Turkey", label: "Turkey" },
  { value: "Czech Republic", label: "Czech Republic" },
  { value: "Romania", label: "Romania" },
  { value: "Czechoslovakia", label: "Czechoslovakia" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Venezuela", label: "Venezuela" },
  { value: "Ireland", label: "Ireland" },
  { value: "Taiwan", label: "Taiwan" },
  { value: "South Korea", label: "South Korea" },
  { value: "Chile", label: "Chile" },
  { value: "Peru", label: "Peru" },
  { value: "Israel", label: "Israel" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Thailand", label: "Thailand" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Scandinavia", label: "Scandinavia" },
  { value: "China", label: "China" },
  {
    value: "German Democratic Republic (GDR)",
    label: "German Democratic Republic (GDR)",
  },
  { value: "Hong Kong", label: "Hong Kong" },
  { value: "Philippines", label: "Philippines" },
  { value: "Croatia", label: "Croatia" },
  { value: "USA & Europe", label: "USA & Europe" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Serbia", label: "Serbia" },
  { value: "Lithuania", label: "Lithuania" },
  {
    value: "Germany, Austria, & Switzerland",
    label: "Germany, Austria, & Switzerland",
  },
  { value: "UK, Europe & US", label: "UK, Europe & US" },
  { value: "Singapore", label: "Singapore" },
  { value: "Slovenia", label: "Slovenia" },
  { value: "Slovakia", label: "Slovakia" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Iceland", label: "Iceland" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Australasia", label: "Australasia" },
  { value: "UK & Ireland", label: "UK & Ireland" },
  { value: "Australia & New Zealand", label: "Australia & New Zealand" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Estonia", label: "Estonia" },
  { value: "USA, Canada & Europe", label: "USA, Canada & Europe" },
  { value: "Benelux", label: "Benelux" },
  { value: "Lebanon", label: "Lebanon" },
  { value: "Panama", label: "Panama" },
  { value: "UK & US", label: "UK & US" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Egypt", label: "Egypt" },
  { value: "Cuba", label: "Cuba" },
  { value: "Latvia", label: "Latvia" },
  { value: "Middle East", label: "Middle East" },
  { value: "Puerto Rico", label: "Puerto Rico" },
  { value: "Kenya", label: "Kenya" },
  { value: "Iran", label: "Iran" },
  { value: "Belarus", label: "Belarus" },
  { value: "Morocco", label: "Morocco" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Barbados", label: "Barbados" },
  { value: "Trinidad & Tobago", label: "Trinidad & Tobago" },
  { value: "Macedonia", label: "Macedonia" },
  { value: "Czech Republic & Slovakia", label: "Czech Republic & Slovakia" },
  { value: "Bosnia & Herzegovina", label: "Bosnia & Herzegovina" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "USA, Canada & UK", label: "USA, Canada & UK" },
  { value: "Algeria", label: "Algeria" },
  { value: "Zimbabwe", label: "Zimbabwe" },
  {
    value: "Singapore, Malaysia & Hong Kong",
    label: "Singapore, Malaysia & Hong Kong",
  },
  { value: "Ghana", label: "Ghana" },
  { value: "Madagascar", label: "Madagascar" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "North America (inc Mexico)", label: "North America (inc Mexico)" },
  { value: "Dominican Republic", label: "Dominican Republic" },
  {
    value: "Congo, Democratic Republic of the",
    label: "Congo, Democratic Republic of the",
  },
  { value: "Reunion", label: "Reunion" },
  { value: "Ivory Coast", label: "Ivory Coast" },
  { value: "France & Benelux", label: "France & Benelux" },
  { value: "Tunisia", label: "Tunisia" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "Zaire", label: "Zaire" },
  { value: "Angola", label: "Angola" },
  { value: "Serbia and Montenegro", label: "Serbia and Montenegro" },
  { value: "Georgia", label: "Georgia" },
  { value: "Malta", label: "Malta" },
  { value: "Germany & Switzerland", label: "Germany & Switzerland" },
  { value: "Asia", label: "Asia" },
  { value: "Angola", label: "Angola" },
  { value: "Serbia and Montenegro", label: "Serbia and Montenegro" },
  { value: "Georgia", label: "Georgia" },
  { value: "Malta", label: "Malta" },
  { value: "Germany & Switzerland", label: "Germany & Switzerland" },
  { value: "Asia", label: "Asia" },
  { value: "Rhodesia", label: "Rhodesia" },
  { value: "Cyprus", label: "Cyprus" },
  { value: "Mozambique", label: "Mozambique" },
  { value: "Singapore & Malaysia", label: "Singapore & Malaysia" },
  { value: "Mauritius", label: "Mauritius" },
  { value: "Zambia", label: "Zambia" },
  { value: "Syria", label: "Syria" },
  { value: "Azerbaijan", label: "Azerbaijan" },
  { value: "Kazakhstan", label: "Kazakhstan" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Senegal", label: "Senegal" },
  { value: "Ethiopia", label: "Ethiopia" },
  { value: "Vietnam", label: "Vietnam" },
  { value: "Guadeloupe", label: "Guadeloupe" },
  { value: "Moldova, Republic of", label: "Moldova, Republic of" },
  { value: "Russia & CIS", label: "Russia & CIS" },
  { value: "UK & France", label: "UK & France" },
  { value: "South Vietnam", label: "South Vietnam" },
  { value: "Bahamas, The", label: "Bahamas, The" },
  { value: "Suriname", label: "Suriname" },
  { value: "UK, Europe & Japan", label: "UK, Europe & Japan" },
  { value: "Haiti", label: "Haiti" },
  { value: "Gulf Cooperation Council", label: "Gulf Cooperation Council" },
  { value: "Faroe Islands", label: "Faroe Islands" },
  { value: "South America", label: "South America" },
  { value: "Cameroon", label: "Cameroon" },
  { value: "South East Asia", label: "South East Asia" },
  { value: "Uzbekistan", label: "Uzbekistan" },
  { value: "Albania", label: "Albania" },
  { value: "Honduras", label: "Honduras" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Martinique", label: "Martinique" },
  { value: "Benin", label: "Benin" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "Curaçao", label: "Curaçao" },
  { value: "Armenia", label: "Armenia" },
  { value: "Andorra", label: "Andorra" },
  { value: "Netherlands Antilles", label: "Netherlands Antilles" },
  { value: "Mali", label: "Mali" },
  { value: "Liechtenstein", label: "Liechtenstein" },
  { value: "Congo, Republic of the", label: "Congo, Republic of the" },
  { value: "Sudan", label: "Sudan" },
  { value: "Guinea", label: "Guinea" },
  { value: "Dahomey", label: "Dahomey" },
  { value: "Burma", label: "Burma" },
  { value: "Uganda", label: "Uganda" },
  { value: "Mongolia", label: "Mongolia" },
  { value: "French Polynesia", label: "French Polynesia" },
  { value: "Nepal", label: "Nepal" },
  { value: "Kosovo", label: "Kosovo" },
  { value: "Cambodia", label: "Cambodia" },
  { value: "Greenland", label: "Greenland" },
  { value: "Virgin Islands", label: "Virgin Islands" },
  { value: "North Korea", label: "North Korea" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Iraq", label: "Iraq" },
  { value: "Austria-Hungary", label: "Austria-Hungary" },
  { value: "Dutch East Indies", label: "Dutch East Indies" },
  { value: "Southern Rhodesia", label: "Southern Rhodesia" },
  { value: "Cape Verde", label: "Cape Verde" },
  { value: "Bermuda", label: "Bermuda" },
  { value: "Isle Of Man", label: "Isle Of Man" },
  { value: "Guyana", label: "Guyana" },
  { value: "Seychelles", label: "Seychelles" },
  { value: "UK & Germany", label: "UK & Germany" },
  { value: "Tanzania", label: "Tanzania" },
  { value: "Central America", label: "Central America" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Libya", label: "Libya" },
  { value: "Montenegro", label: "Montenegro" },
  { value: "Jordan", label: "Jordan" },
  { value: "Palestine", label: "Palestine" },
  { value: "Antigua & Barbuda", label: "Antigua & Barbuda" },
  { value: "Belgian Congo", label: "Belgian Congo" },
  {
    value: "Singapore, Malaysia, Hong Kong & Thailand",
    label: "Singapore, Malaysia, Hong Kong & Thailand",
  },
  { value: "Gabon", label: "Gabon" },
  { value: "Monaco", label: "Monaco" },
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Togo", label: "Togo" },
  { value: "Belize", label: "Belize" },
  { value: "Cayman Islands", label: "Cayman Islands" },
  { value: "Yemen", label: "Yemen" },
  { value: "Fiji", label: "Fiji" },
  { value: "New Caledonia", label: "New Caledonia" },
  { value: "Papua New Guinea", label: "Papua New Guinea" },
  { value: "Aruba", label: "Aruba" },
  { value: "Laos", label: "Laos" },
  { value: "French Guiana", label: "French Guiana" },
  { value: "Upper Volta", label: "Upper Volta" },
  { value: "North & South America", label: "North & South America" },
  { value: "East Timor", label: "East Timor" },
  { value: "Dominica", label: "Dominica" },
  { value: "San Marino", label: "San Marino" },
  { value: "Africa", label: "Africa" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Namibia", label: "Namibia" },
  { value: "Sierra Leone", label: "Sierra Leone" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan" },
  { value: "Ottoman Empire", label: "Ottoman Empire" },
  { value: "UK, Europe & Israel", label: "UK, Europe & Israel" },
  { value: "Brunei", label: "Brunei" },
  { value: "Turkmenistan", label: "Turkmenistan" },
  { value: "Eritrea", label: "Eritrea" },
  { value: "Jersey", label: "Jersey" },
  { value: "Guernsey", label: "Guernsey" },
  { value: "Botswana", label: "Botswana" },
  { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
  { value: "Guam", label: "Guam" },
  { value: "Central African Republic", label: "Central African Republic" },
  { value: "Korea (pre-1945)", label: "Korea (pre-1945)" },
  { value: "Qatar", label: "Qatar" },
  { value: "Somalia", label: "Somalia" },
  { value: "Liberia", label: "Liberia" },
  { value: "Sint Maarten", label: "Sint Maarten" },
  { value: "Macau", label: "Macau" },
  { value: "Grenada", label: "Grenada" },
  { value: "Saint Lucia", label: "Saint Lucia" },
  {
    value: "Protectorate of Bohemia and Moravia",
    label: "Protectorate of Bohemia and Moravia",
  },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Indochina", label: "Indochina" },
  { value: "Maldives", label: "Maldives" },
  { value: "Niger", label: "Niger" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Gambia, The", label: "Gambia, The" },
  {
    value: "Saint Vincent and the Grenadines",
    label: "Saint Vincent and the Grenadines",
  },
  { value: "Malawi", label: "Malawi" },
  { value: "Cook Islands", label: "Cook Islands" },
  { value: "Comoros", label: "Comoros" },
  { value: "Gibraltar", label: "Gibraltar" },
  { value: "Palau", label: "Palau" },
  { value: "Vatican City", label: "Vatican City" },
  { value: "Bohemia", label: "Bohemia" },
  { value: "Rwanda", label: "Rwanda" },
  { value: "Samoa", label: "Samoa" },
  { value: "Oman", label: "Oman" },
  { value: "Tajikistan", label: "Tajikistan" },
  { value: "Abkhazia", label: "Abkhazia" },
  { value: "Mayotte", label: "Mayotte" },
  { value: "South Pacific", label: "South Pacific" },
  { value: "British Virgin Islands", label: "British Virgin Island" },
];
